import React from 'react';

export interface GenericPDFData {
  id: string;
  company_name: string;
  email: string;
  title: string;
  subtitle?: string;
  description: string;
  resourceName: string;
  data?: any;
}

interface GenericLeadMagnetPDFProps {
  data: GenericPDFData;
}

export default function GenericLeadMagnetPDF({ data }: GenericLeadMagnetPDFProps) {
  const logoUrl = 'https://risclens.com/logo/logo-wordmark.png';

  return (
    <html>
      <head>
        <meta charSet="UTF-8" />
        <title>{data.title} - {data.company_name}</title>
        <style>{`
          body { font-family: 'Helvetica Neue', Arial, sans-serif; color: #1e293b; padding: 40px; line-height: 1.6; }
          .header { text-align: center; border-bottom: 2px solid #0ea5e9; padding-bottom: 20px; margin-bottom: 30px; }
          .title { font-size: 24pt; font-weight: bold; color: #0f172a; margin-bottom: 5px; }
          .subtitle { font-size: 14pt; color: #64748b; }
          .hero-box { background: #f0f9ff; border: 1px solid #bae6fd; border-radius: 12px; padding: 30px; margin-bottom: 30px; }
          .section-title { font-size: 16pt; font-weight: bold; color: #0369a1; margin: 25px 0 15px; border-bottom: 1px solid #e2e8f0; padding-bottom: 5px; }
          .content-box { background: #ffffff; border: 1px solid #e2e8f0; border-radius: 8px; padding: 20px; margin-bottom: 20px; }
          .footer { margin-top: 50px; font-size: 9pt; color: #94a3b8; text-align: center; border-top: 1px solid #e2e8f0; padding-top: 20px; }
          .badge { display: inline-block; padding: 4px 12px; background: #0ea5e9; color: white; border-radius: 20px; font-size: 10pt; font-weight: bold; margin-bottom: 15px; }
          .data-table { width: 100%; border-collapse: collapse; margin-top: 15px; }
          .data-table th, .data-table td { border: 1px solid #e2e8f0; padding: 10px; text-align: left; }
          .data-table th { background: #f8fafc; font-weight: bold; }
        `}</style>
      </head>
      <body>
        <div className="header">
          <img src={logoUrl} alt="RiscLens" style={{ height: '56px', marginBottom: '10px' }} />
          <div className="title">{data.title}</div>
          {data.subtitle && <div className="subtitle">{data.subtitle}</div>}
        </div>

        <div className="hero-box">
          <div className="badge">Premium Resource</div>
          <h2 style={{ margin: '0 0 10px 0', color: '#0369a1' }}>{data.resourceName}</h2>
          <p style={{ margin: 0, fontSize: '12pt' }}>
            {data.description}
          </p>
        </div>

        <div className="section">
          <div className="section-title">Recipient Information</div>
          <div className="content-box">
            <p><strong>Company:</strong> {data.company_name}</p>
            <p><strong>Requested by:</strong> {data.email}</p>
            <p><strong>Date Generated:</strong> {new Date().toLocaleDateString()}</p>
            <p><strong>Resource ID:</strong> {data.id}</p>
          </div>
        </div>

        {data.data && Object.keys(data.data).length > 0 && (
          <div className="section">
            <div className="section-title">Configuration & Context</div>
            <div className="content-box">
              <table className="data-table">
                <thead>
                  <tr>
                    <th>Parameter</th>
                    <th>Value</th>
                  </tr>
                </thead>
                <tbody>
                  {Object.entries(data.data).map(([key, value]) => (
                    <tr key={key}>
                      <td style={{ textTransform: 'capitalize' }}>{key.replace(/_/g, ' ')}</td>
                      <td>{typeof value === 'object' ? JSON.stringify(value) : String(value)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}

        <div className="section">
          <div className="section-title">Next Steps</div>
          <div className="content-box">
            <ul style={{ paddingLeft: '20px' }}>
              <li>Schedule a walkthrough with a RiscLens compliance expert.</li>
              <li>Review these requirements with your internal security stakeholders.</li>
              <li>Integrate these templates into your 2026 audit preparation cycle.</li>
              <li>Visit <strong>risclens.com/admin</strong> to manage your compliance roadmap.</li>
            </ul>
          </div>
        </div>

        <div className="footer">
          Confidential Resource | Generated by RiscLens<br />
          © 2026 RiscLens Inc. All rights reserved.
        </div>
      </body>
    </html>
  );
}
