export interface EvidenceGuide {
  slug: string;
  title: string;
  description: string;
  readinessLink: string;
  checklist: string[];
  mistakes: string[];
  steps: string[];
  faqs: { question: string; answer: string }[];
}

export const evidenceGuides: EvidenceGuide[] = [
  {
    slug: 'access-control',
    title: 'SOC 2 Evidence for Access Control: What to Collect',
    description: 'Access control evidence shows how you grant, review, and revoke access to systems, data, and tooling.',
    readinessLink: '/soc-2-readiness/access-control',
    checklist: [
      'User provisioning and deprovisioning tickets with approvals',
      'Access review records for key systems (app, DB, cloud)',
      'SSO and MFA configuration screenshots or exports',
      'Role definitions and least-privilege mapping',
      'Break-glass access procedures and logs',
      'Service account inventories and rotation records',
      'Logging of admin actions for sensitive systems',
      'Evidence of periodic credential rotation',
      'Contractor access tracking and end dates',
      'VPN or network access rules with approvals',
    ],
    mistakes: [
      'Missing approvals for new admin access',
      'Stale accounts left active after offboarding',
      'No proof of MFA enforcement across all users',
      'Service accounts without owners or rotation cadence',
      'Lack of logs for privileged actions',
    ],
    steps: [
      'Export current users and roles from identity and key systems.',
      'Run and document an access review with sign-off.',
      'Capture MFA/SSO settings and enforcement screenshots.',
      'Close stale accounts and document remediation.',
      'Store evidence with timestamps and owners for audit reuse.',
    ],
    faqs: [
      { question: 'How recent should access reviews be?', answer: 'Quarterly is common. Provide the latest review with approvals and remediation notes.' },
      { question: 'Do we need screenshots or exports?', answer: 'Either works—ensure it shows users, roles, and MFA status with dates.' },
      { question: 'How do we handle contractors?', answer: 'Track start/end dates, least privilege, and confirm removal at end of term.' },
      { question: 'Is SSO required?', answer: 'It is strongly expected. Show where SSO is enabled and where exceptions exist.' },
      { question: 'What about service accounts?', answer: 'Provide inventory, owners, rotation cadence, and how credentials are protected.' },
      { question: 'Do we need to log admin actions?', answer: 'Yes—collect logs for privileged actions on critical systems.' },
    ],
  },
  {
    slug: 'change-management',
    title: 'SOC 2 Evidence for Change Management: What to Collect',
    description: 'Change management evidence shows safe delivery to production with approvals, testing, and rollback readiness.',
    readinessLink: '/soc-2-readiness/change-management',
    checklist: [
      'Pull requests with approvals and CI results',
      'Change tickets with risk/impact noted',
      'Release approvals or deployment change records',
      'Rollback plans or automated rollback configurations',
      'Evidence of emergency change handling',
      'Separation of duties for code review and deploy',
      'Testing results or staging sign-off records',
      'Deploy logs showing who deployed and when',
      'Post-deploy validation or monitoring checks',
      'Documented change freeze windows (if applicable)',
    ],
    mistakes: [
      'No approval evidence for critical changes',
      'Missing rollback references',
      'Merged code without CI or testing proof',
      'Emergency changes not documented post-fact',
      'Deploy permissions not reviewed regularly',
    ],
    steps: [
      'Collect recent pull requests showing approvals and CI.',
      'Export deployment logs for the observation period.',
      'Document how emergency changes are recorded and reviewed.',
      'Include rollback procedures and evidence they are tested.',
      'Store artifacts with timestamps tied to change IDs.',
    ],
    faqs: [
      { question: 'How many changes should we sample?', answer: 'Auditors typically sample several changes per period. Provide a consistent sample with full evidence.' },
      { question: 'Do we need a formal CAB?', answer: 'Not always—show risk assessment, approvals, and documented deploy process. Light CABs or automated approvals can work.' },
      { question: 'What about infrastructure changes?', answer: 'Include IaC changes and approvals for infrastructure impacting production.' },
      { question: 'How do we show separation of duties?', answer: 'Provide evidence that the deployer differs from the author or that approvals are independent.' },
      { question: 'Are emergency changes allowed?', answer: 'Yes, with documented approvals afterward and clear rollback validation.' },
      { question: 'Do we need screenshots or exports?', answer: 'Provide exports where possible; screenshots work if they include timestamps and identifiers.' },
    ],
  },
  {
    slug: 'logging-monitoring',
    title: 'SOC 2 Evidence for Logging and Monitoring: What to Collect',
    description: 'Logging and monitoring evidence demonstrates detection coverage, alerting, and response to events.',
    readinessLink: '/soc-2-readiness/logging-and-monitoring',
    checklist: [
      'Log source inventory with retention settings',
      'Alert rules and severity tiers',
      'Sample alerts with timestamps and responders',
      'Runbooks for common alerts',
      'Evidence of log integrity or tamper resistance',
      'Coverage of admin actions and authentication events',
      'Monitoring dashboards for availability and errors',
      'On-call schedules and escalation paths',
      'Evidence of alert testing or drills',
      'Integration with incident management tooling',
    ],
    mistakes: [
      'Incomplete log sources or missing retention settings',
      'No proof alerts are reviewed or escalated',
      'Gaps in admin or authentication logging',
      'Runbooks not aligned to alert rules',
      'No testing of alerting paths',
    ],
    steps: [
      'List log sources and confirm retention and access controls.',
      'Provide sample alerts with evidence of review or response.',
      'Share runbooks and on-call schedules.',
      'Validate admin/auth logging coverage and include samples.',
      'Document how alerts integrate with incident management.',
    ],
    faqs: [
      { question: 'How long should we retain logs?', answer: 'Depends on risk and contracts; 90 days online plus archive is common. Document your policy and settings.' },
      { question: 'Do we need to log admin actions?', answer: 'Yes—include privileged actions, authentication, and key configuration changes.' },
      { question: 'How do we show alerts are handled?', answer: 'Provide sample alerts with timestamps, responders, and resolutions. Include on-call rotations.' },
      { question: 'What about SIEM tuning?', answer: 'Document rule reviews, suppression, and tuning cadence to reduce noise while keeping coverage.' },
      { question: 'Do we need to simulate incidents?', answer: 'Tabletops or alert tests help show readiness. Provide evidence of recent exercises.' },
      { question: 'How do we secure logs?', answer: 'Limit access, enable integrity controls where possible, and monitor for tampering.' },
    ],
  },
  {
    slug: 'incident-response',
    title: 'SOC 2 Evidence for Incident Response: What to Collect',
    description: 'Incident response evidence shows how you detect, triage, and communicate security events.',
    readinessLink: '/soc-2-readiness/incident-response',
    checklist: [
      'Incident response plan and roles',
      'Runbooks for common scenarios',
      'Tabletop exercise records and outcomes',
      'Incident tickets with timelines and communications',
      'Post-incident reviews and action items',
      'On-call rotation and escalation paths',
      'Communication templates for customers/partners',
      'Links to logging/monitoring evidence used in incidents',
      'Evidence of containment and recovery steps',
      'Lessons learned tracking and verification',
    ],
    mistakes: [
      'No proof of exercises or testing',
      'Gaps in communication plans',
      'Missing action item follow-up',
      'Unclear roles during incidents',
      'Lack of linkage between alerts and incidents',
    ],
    steps: [
      'Keep an updated IR plan with owners and contact paths.',
      'Document at least one recent tabletop and outcomes.',
      'Provide a sanitized incident ticket showing timeline and actions.',
      'Track lessons learned and show completed follow-ups.',
      'Store evidence with dates and owners for reuse.',
    ],
    faqs: [
      { question: 'Do we need real incident evidence?', answer: 'If available, sanitize and share. Otherwise, provide tabletop exercises and runbooks.' },
      { question: 'How often should we run exercises?', answer: 'At least annually; quarterly is better for high-risk teams.' },
      { question: 'Who should be on the IR team?', answer: 'Security, engineering, IT, communications, and leadership. Define roles and backups.' },
      { question: 'How do we show communication readiness?', answer: 'Provide templates, contact trees, and evidence of past stakeholder updates.' },
      { question: 'Do we need customer notifications?', answer: 'If applicable, document thresholds and examples. Keep templates ready.' },
      { question: 'How do we connect alerts to incidents?', answer: 'Include alert references in incident tickets and track handoffs from detection to response.' },
    ],
  },
  {
    slug: 'vendor-management',
    title: 'SOC 2 Evidence for Vendor Management: What to Collect',
    description: 'Vendor management evidence demonstrates how you assess, approve, and monitor third parties.',
    readinessLink: '/soc-2-readiness/vendor-management',
    checklist: [
      'Vendor inventory with criticality classification',
      'Security reviews or questionnaires with dates',
      'SOC reports or attestations with management responses',
      'Contract security exhibits and DPAs',
      'Access controls for vendors and support accounts',
      'Monitoring or SLA review records',
      'Issue tracking and remediation follow-up',
      'Offboarding evidence for terminated vendors',
      'Owner assignments per vendor',
      'Data flow mapping per critical vendor',
    ],
    mistakes: [
      'No central vendor list or ownership',
      'Expired SOC reports without review',
      'Missing documentation of security exhibits/DPAs',
      'Vendors left with lingering access',
      'No follow-up on identified issues',
    ],
    steps: [
      'Build a vendor inventory with criticality and owners.',
      'Collect recent SOC reports/attestations and document reviews.',
      'Capture contract security terms and DPAs.',
      'Review access for vendors and remove stale accounts.',
      'Track remediation items and renewal dates.',
    ],
    faqs: [
      { question: 'How often should we review vendors?', answer: 'At least annually for critical vendors; more often for high-risk providers.' },
      { question: 'Do we need SOC reports for every vendor?', answer: 'Prioritize critical vendors. For others, gather attestations or questionnaires as appropriate.' },
      { question: 'How do we track remediation?', answer: 'Maintain an issue log with owners and due dates. Tie it to contract renewals where possible.' },
      { question: 'What about sub-processors?', answer: 'Document their role, data processed, and oversight approach. Include them in inventories and reviews.' },
      { question: 'How do we handle vendor access?', answer: 'Use least privilege, time-bound access, and regular reviews. Log vendor actions where possible.' },
      { question: 'Is a DPA required?', answer: 'If personal data is processed, yes. Keep executed DPAs and reference them in vendor files.' },
    ],
  },
  {
    slug: 'business-continuity',
    title: 'SOC 2 Evidence for Business Continuity: What to Collect',
    description: 'Business continuity evidence shows how you plan for and recover from disruptions while keeping services available.',
    readinessLink: '/soc-2-readiness/business-continuity',
    checklist: [
      'Business impact analysis or priority service list',
      'Documented recovery objectives (RPO/RTO)',
      'Backup schedules and restore tests',
      'Disaster recovery plans and roles',
      'Tabletop or DR test records with outcomes',
      'Redundancy/availability architecture diagrams',
      'Communication plans for customers and partners',
      'Incident/BCP playbooks for major scenarios',
      'Evidence of dependency reviews for critical vendors',
      'Post-test action items and tracking',
    ],
    mistakes: [
      'No recent DR test evidence',
      'Unclear RPO/RTO targets',
      'Backups untested or undocumented',
      'No communication plan for major incidents',
      'Critical vendor dependencies not documented',
    ],
    steps: [
      'Document critical services and RPO/RTO targets.',
      'Provide backup and restore test evidence.',
      'Run a DR or continuity exercise and record outcomes.',
      'Capture architecture showing redundancy and failover.',
      'Track action items and verify completion.',
    ],
    faqs: [
      { question: 'How often should we test DR?', answer: 'Annually at minimum. High-availability services may test more frequently.' },
      { question: 'Do we need full failover tests?', answer: 'If feasible. Otherwise, tabletop or component-level tests with documented outcomes and follow-ups.' },
      { question: 'What about cloud-managed services?', answer: 'Include their SLAs, regions, and failover capabilities in your plan and evidence.' },
      { question: 'How do we show backups are working?', answer: 'Provide restore test results, screenshots/logs, and retention settings.' },
      { question: 'Do we include vendors in continuity?', answer: 'Yes—document critical suppliers, SLAs, and contingency plans if they fail.' },
      { question: 'How do we keep plans current?', answer: 'Assign owners, review quarterly/annually, and update after significant changes or incidents.' },
    ],
  },
];

export function getEvidenceGuide(slug: string) {
  return evidenceGuides.find((guide) => guide.slug === slug);
}
