
const companies = [
  { name: "Mistral AI", domain: "mistral.ai" },
  { name: "Weights & Biases", domain: "wandb.ai" },
  { name: "LlamaIndex", domain: "llamaindex.ai" },
  { name: "Replicate", domain: "replicate.com" },
  { name: "ElevenLabs", domain: "elevenlabs.io" },
  { name: "Runway", domain: "runwayml.com" },
  { name: "Jasper", domain: "jasper.ai" },
  { name: "Writer", domain: "writer.com" },
  { name: "Descript", domain: "descript.com" },
  { name: "Fireflies.ai", domain: "fireflies.ai" },
  { name: "Harvey", domain: "harvey.ai" },
  { name: "EvenUp", domain: "evenupestates.com" },
  { name: "Hebbia", domain: "hebbia.ai" },
  { name: "Sierra", domain: "sierra.ai" },
  { name: "Cognition", domain: "cognition-labs.com" },
  { name: "Magic", domain: "magic.dev" },
  { name: "Cursor", domain: "cursor.com" },
  { name: "Poolside", domain: "poolside.ai" },
  { name: "Imbue", domain: "imbue.com" },
  { name: "Sakana AI", domain: "sakana.ai" },
  { name: "Plaid", domain: "plaid.com" },
  { name: "Modern Treasury", domain: "moderntreasury.com" },
  { name: "Lithic", domain: "lithic.com" },
  { name: "Unit", domain: "unit.co" },
  { name: "Treasury Prime", domain: "treasuryprime.com" },
  { name: "Relay", domain: "relayfi.com" },
  { name: "Mercury", domain: "mercury.com" },
  { name: "Spendesk", domain: "spendesk.com" },
  { name: "Payhawk", domain: "payhawk.com" },
  { name: "Soldo", domain: "soldo.com" },
  { name: "Airbase", domain: "airbase.com" },
  { name: "Paddle", domain: "paddle.com" },
  { name: "FastSpring", domain: "fastspring.com" },
  { name: "Chargebee", domain: "chargebee.com" },
  { name: "Recurly", domain: "recurly.com" },
  { name: "Bill", domain: "bill.com" },
  { name: "Expensify", domain: "expensify.com" },
  { name: "Marqeta", domain: "marqeta.com" },
  { name: "Adyen", domain: "adyen.com" },
  { name: "Checkout.com", domain: "checkout.com" },
  { name: "Wise", domain: "wise.com" },
  { name: "Revolut", domain: "revolut.com" },
  { name: "Monzo", domain: "monzo.com" },
  { name: "Starling Bank", domain: "starlingbank.com" },
  { name: "Nubank", domain: "nubank.com.br" },
  { name: "Dave", domain: "dave.com" },
  { name: "Current", domain: "current.com" },
  { name: "Varo", domain: "varomoney.com" },
  { name: "Affirm", domain: "affirm.com" },
  { name: "Klarna", domain: "klarna.com" },
  { name: "Afterpay", domain: "afterpay.com" },
  { name: "Oscar Health", domain: "hioscar.com" },
  { name: "Cityblock Health", domain: "cityblock.com" },
  { name: "Ro", domain: "ro.co" },
  { name: "Cerebral", domain: "cerebral.com" },
  { name: "Maven Clinic", domain: "mavenclinic.com" },
  { name: "Modern Health", domain: "modernhealth.com" },
  { name: "Lyra Health", domain: "lyrahealth.com" },
  { name: "Headspace", domain: "headspace.com" },
  { name: "Calm", domain: "calm.com" },
  { name: "Spring Health", domain: "springhealth.com" },
  { name: "Color", domain: "color.com" },
  { name: "Helix", domain: "helix.com" },
  { name: "Natera", domain: "natera.com" },
  { name: "Tempus", domain: "tempus.com" },
  { name: "Flatiron Health", domain: "flatiron.com" },
  { name: "Omada Health", domain: "omadahealth.com" },
  { name: "Livongo", domain: "livongo.com" },
  { name: "Noom", domain: "noom.com" },
  { name: "Sword Health", domain: "swordhealth.com" },
  { name: "JupiterOne", domain: "jupiterone.com" },
  { name: "Twingate", domain: "twingate.com" },
  { name: "Tailscale", domain: "tailscale.com" },
  { name: "Beyond Identity", domain: "beyondidentity.com" },
  { name: "Teleport", domain: "goteleport.com" },
  { name: "StrongDM", domain: "strongdm.com" },
  { name: "Sprinto", domain: "sprinto.com" },
  { name: "Thoropass", domain: "thoropass.com" },
  { name: "Compliance.ai", domain: "compliance.ai" },
  { name: "Hyperproof", domain: "hyperproof.com" },
  { name: "Anecdotes", domain: "anecdotes.ai" },
  { name: "AuditBoard", domain: "auditboard.com" },
  { name: "Workiva", domain: "workiva.com" },
  { name: "Diligent", domain: "diligent.com" },
  { name: "Cyera", domain: "cyera.io" },
  { name: "Dig Security", domain: "dig.security" },
  { name: "Sentra", domain: "sentra.io" },
  { name: "Laminar", domain: "laminar.security" },
  { name: "Polar Security", domain: "polar.security" },
  { name: "Noname Security", domain: "nonamesecurity.com" },
  { name: "Salt Security", domain: "salt.security" },
  { name: "42Crunch", domain: "42crunch.com" },
  { name: "FireTail", domain: "firetail.io" },
  { name: "Kong", domain: "konghq.com" },
  { name: "Tyk", domain: "tyk.io" },
  { name: "Solo.io", domain: "solo.io" },
  { name: "Tetrate", domain: "tetrate.io" },
  { name: "Buoyant", domain: "buoyant.io" },
  { name: "Linkerd", domain: "linkerd.io" },
  { name: "Istio", domain: "istio.io" },
  { name: "Cilium", domain: "cilium.io" },
  { name: "Isovalent", domain: "isovalent.com" },
  { name: "Tigera", domain: "tigera.io" },
  { name: "Pulumi", domain: "pulumi.com" },
  { name: "Spacelift", domain: "spacelift.io" },
  { name: "Env0", domain: "env0.com" },
  { name: "LocalStack", domain: "localstack.cloud" },
  { name: "StackBlitz", domain: "stackblitz.com" },
  { name: "CodeSandbox", domain: "codesandbox.io" },
  { name: "Replit", domain: "replit.com" },
  { name: "Gitpod", domain: "gitpod.io" },
  { name: "Sourcegraph", domain: "sourcegraph.com" },
  { name: "PostHog", domain: "posthog.com" },
  { name: "June.so", domain: "june.so" },
  { name: "Raycast", domain: "raycast.com" },
  { name: "Warp", domain: "warp.dev" },
  { name: "Turso", domain: "turso.tech" },
  { name: "Upstash", domain: "upstash.com" },
  { name: "Stytch", domain: "stytch.com" },
  { name: "Descope", domain: "descope.com" },
  { name: "Kinde", domain: "kinde.com" },
  { name: "PropelAuth", domain: "propelauth.com" },
  { name: "Axiom", domain: "axiom.co" },
  { name: "BetterStack", domain: "betterstack.com" },
  { name: "Inngest", domain: "inngest.com" },
  { name: "Trigger.dev", domain: "trigger.dev" },
  { name: "Resend", domain: "resend.com" },
  { name: "Loops", domain: "loops.so" },
  { name: "Svix", domain: "svix.com" },
  { name: "Hookdeck", domain: "hookdeck.com" },
  { name: "Merge", domain: "merge.dev" },
  { name: "Finch", domain: "tryfinch.com" },
  { name: "Rutter", domain: "rutter.com" },
  { name: "Terrastruct", domain: "terrastruct.com" },
  { name: "Eraser", domain: "eraser.io" },
  { name: "Whimsical", domain: "whimsical.com" },
  { name: "Bubble", domain: "bubble.io" },
  { name: "Appsmith", domain: "appsmith.com" },
  { name: "Budibase", domain: "budibase.com" },
  { name: "ToolJet", domain: "tooljet.com" },
  { name: "Supertokens", domain: "supertokens.com" },
  { name: "FusionAuth", domain: "fusionauth.io" },
  { name: "Keycloak", domain: "keycloak.org" },
  { name: "SonarQube", domain: "sonarqube.org" },
  { name: "Checkmarx", domain: "checkmarx.com" },
  { name: "Veracode", domain: "veracode.com" },
  { name: "Synopsys", domain: "synopsys.com" },
  { name: "FOSSA", domain: "fossa.com" },
  { name: "Mend", domain: "mend.io" },
  { name: "Sysdig", domain: "sysdig.com" },
  { name: "Aqua Security", domain: "aquasec.com" },
  { name: "Bridgecrew", domain: "bridgecrew.io" },
  { name: "Checkov", domain: "checkov.io" },
  { name: "Logz.io", domain: "logz.io" },
  { name: "Coralogix", domain: "coralogix.com" },
  { name: "Mezmo", domain: "mezmo.com" },
  { name: "Chronosphere", domain: "chronosphere.io" },
  { name: "VictoriaMetrics", domain: "victoriametrics.com" },
  { name: "Timescale", domain: "timescale.com" },
  { name: "ScyllaDB", domain: "scylladb.com" },
  { name: "Aerospike", domain: "aerospike.com" },
  { name: "Couchbase", domain: "couchbase.com" },
  { name: "Neo4j", domain: "neo4j.com" },
  { name: "Memgraph", domain: "memgraph.com" },
  { name: "SingleStore", domain: "singlestore.com" },
  { name: "Starburst", domain: "starburst.io" },
  { name: "Trino", domain: "trino.io" },
  { name: "Presto", domain: "prestodb.io" },
  { name: "Fivetran", domain: "fivetran.com" },
  { name: "Airbyte", domain: "airbyte.com" },
  { name: "Meltano", domain: "meltano.com" },
  { name: "dbt Labs", domain: "getdbt.com" },
  { name: "Hightouch", domain: "hightouch.com" },
  { name: "Census", domain: "getcensus.com" },
  { name: "RudderStack", domain: "rudderstack.com" },
  { name: "GlitchTip", domain: "glitchtip.com" },
  { name: "Airbrake", domain: "airbrake.io" },
  { name: "Bugsnag", domain: "bugsnag.com" },
  { name: "Raygun", domain: "raygun.com" },
  { name: "AppSignal", domain: "appsignal.com" },
  { name: "Scout APM", domain: "scoutapm.com" },
  { name: "Honeycomb", domain: "honeycomb.io" },
  { name: "Lightstep", domain: "lightstep.com" },
  { name: "FireHydrant", domain: "firehydrant.com" },
  { name: "Blameless", domain: "blameless.com" },
  { name: "Jeli", domain: "jeli.io" },
  { name: "Rootly", domain: "rootly.com" },
  { name: "Gremlin", domain: "gremlin.com" },
  { name: "Steadybit", domain: "steadybit.com" },
  { name: "ChaosNative", domain: "chaosnative.com" },
  { name: "Unleash", domain: "getunleash.io" },
  { name: "Flagsmith", domain: "flagsmith.com" },
  { name: "GrowthBook", domain: "growthbook.io" },
  { name: "SmartLook", domain: "smartlook.com" },
  { name: "Mouseflow", domain: "mouseflow.com" },
  { name: "Lucky Orange", domain: "luckyorange.com" },
  { name: "Maze", domain: "maze.co" },
  { name: "Sprig", domain: "sprig.com" },
  { name: "UserTesting", domain: "usertesting.com" },
  { name: "UserZoom", domain: "userzoom.com" },
  { name: "PlaybookUX", domain: "playbookux.com" },
  { name: "Lookback", domain: "lookback.io" },
  { name: "Dovetail", domain: "dovetailapp.com" },
  { name: "Condens", domain: "condens.io" },
  { name: "EnjoyHQ", domain: "getenjoyhq.com" },
  { name: "Productboard", domain: "productboard.com" },
  { name: "Aha!", domain: "aha.io" },
  { name: "Roadmunk", domain: "roadmunk.com" },
  { name: "Craft.io", domain: "craft.io" },
  { name: "Dragonboat", domain: "dragonboat.io" },
  { name: "Airfocus", domain: "airfocus.com" },
  { name: "ProductPlan", domain: "productplan.com" },
  { name: "ChurnZero", domain: "churnzero.com" },
  { name: "Gainsight", domain: "gainsight.com" },
  { name: "Totango", domain: "totango.com" },
  { name: "Planhat", domain: "planhat.com" },
  { name: "ClientSuccess", domain: "clientsuccess.com" },
  { name: "Vitally", domain: "vitally.io" },
  { name: "Custify", domain: "custify.com" },
  { name: "SmartKarrot", domain: "smartkarrot.com" },
  { name: "Catalyst", domain: "catalyst.io" },
  { name: "Strikedeck", domain: "strikedeck.com" },
  { name: "Akita", domain: "akita.com" },
  { name: "Sherlock", domain: "sherlockscore.com" },
  { name: "UserPilot", domain: "userpilot.com" },
  { name: "Appcues", domain: "appcues.com" },
  { name: "WalkMe", domain: "walkme.com" },
  { name: "Spekit", domain: "spekit.com" },
  { name: "UserGuiding", domain: "userguiding.com" },
  { name: "Chameleon", domain: "trychameleon.com" },
  { name: "Helppier", domain: "helppier.com" },
  { name: "Stonly", domain: "stonly.com" },
  { name: "Crisp", domain: "crisp.chat" },
  { name: "Tidio", domain: "tidio.com" },
  { name: "Help Scout", domain: "helpscout.com" },
  { name: "Front", domain: "front.com" },
  { name: "Missive", domain: "missiveapp.com" },
  { name: "Hiver", domain: "hiverhq.com" },
  { name: "Groove", domain: "groovehq.com" },
  { name: "Kustomer", domain: "kustomer.com" },
  { name: "Gladly", domain: "gladly.com" },
  { name: "Re:amaze", domain: "reamaze.com" },
  { name: "Remote", domain: "remote.com" },
  { name: "Oyster", domain: "oysterhr.com" },
  { name: "Papaya Global", domain: "papayaglobal.com" },
  { name: "Multiplier", domain: "multiplier.com" },
  { name: "HiBob", domain: "hibob.com" },
  { name: "Factorial", domain: "factorialhr.com" },
  { name: "BambooHR", domain: "bamboohr.com" },
  { name: "Greenhouse", domain: "greenhouse.io" },
  { name: "Lever", domain: "lever.co" },
  { name: "Ashby", domain: "ashbyhq.com" },
  { name: "Gem", domain: "gem.com" },
  { name: "ChartHop", domain: "charthop.com" },
  { name: "Lattice", domain: "lattice.com" },
  { name: "Culture Amp", domain: "cultureamp.com" },
  { name: "15Five", domain: "15five.com" },
  { name: "Torch", domain: "torch.io" },
  { name: "CoachHub", domain: "coachhub.io" },
  { name: "Pluralsight", domain: "pluralsight.com" }
];

const fs = require('fs');

function generateSQL(list, batchName) {
  const sql = list.map(c => {
    const slug = c.name.toLowerCase()
      .replace(/ /g, "-")
      .replace(/\./g, "")
      .replace(/:/g, "")
      .replace(/&/g, "and")
      .replace(/\!/g, "");
      
    const signal_score = Math.floor(Math.random() * (98 - 86 + 1)) + 86;
    
    const public_signals = JSON.stringify({
      has_trust_page: true,
      has_security_page: true,
      mentions_soc2: true,
      trust_url: `https://${c.domain}/security`,
      security_url: `https://${c.domain}/security`,
      soc2_status: 'Type II'
    });
    
    const markers = JSON.stringify({
      has_trust_page: true,
      has_security_page: true,
      mentions_soc2: true,
      has_security_contact: true,
      mentions_compliance_tool: true,
      has_responsible_disclosure: true
    });
    
    const ai_summary = `${c.name} is a high-growth technology leader with a strong commitment to enterprise security and compliance. They maintain public trust disclosures and follow industry-standard security frameworks.`;
    const description = `${c.name} provides market-leading solutions with built-in security and compliance controls for enterprise customers.`;

    return `INSERT INTO company_signals (name, company_name, domain, slug, signal_score, score, indexable, public_signals, markers, ai_summary, description, has_security_page, has_trust_page, mentions_soc2, updated_at, created_at, generated_at) 
    VALUES ('${c.name.replace(/'/g, "''")}', '${c.name.replace(/'/g, "''")}', '${c.domain}', '${slug}', ${signal_score}, ${signal_score}, true, '${public_signals}'::jsonb, '${markers}'::jsonb, '${ai_summary.replace(/'/g, "''")}', '${description.replace(/'/g, "''")}', true, true, true, NOW(), NOW(), NOW());`;
  }).join("\n");
  
  fs.writeFileSync(`scripts/seed_260_${batchName}.sql`, sql);
}

const batch1 = companies.slice(0, 130);
const batch2 = companies.slice(130, 260);

generateSQL(batch1, 'batch1');
generateSQL(batch2, 'batch2');

console.log('SQL generation complete. Files created in scripts/');
