-- =============================================================================
-- ADDITIONAL COMPANY SIGNALS - BATCH 2
-- Date: 2026-01-17
-- Purpose: Add 350+ more companies to reach 1000 total
-- =============================================================================

INSERT INTO company_signals (name, slug, domain, description, indexable) VALUES
-- Enterprise Software & B2B SaaS
('Slack', 'slack', 'slack.com', 'Business communication platform', true),
('Asana', 'asana', 'asana.com', 'Work management platform', true),
('Monday.com', 'monday', 'monday.com', 'Work OS platform', true),
('ClickUp', 'clickup', 'clickup.com', 'Productivity platform', true),
('Wrike', 'wrike', 'wrike.com', 'Collaborative work management', true),
('Smartsheet', 'smartsheet', 'smartsheet.com', 'Work execution platform', true),
('Basecamp', 'basecamp', 'basecamp.com', 'Project management tool', true),
('TeamGantt', 'teamgantt', 'teamgantt.com', 'Project scheduling', true),
('Trello', 'trello', 'trello.com', 'Visual collaboration tool', true),
('Jira', 'jira', 'atlassian.com/jira', 'Issue tracking platform', true),
('Confluence', 'confluence', 'atlassian.com/confluence', 'Team collaboration wiki', true),
('HubSpot', 'hubspot', 'hubspot.com', 'CRM and marketing platform', true),
('Salesforce', 'salesforce', 'salesforce.com', 'CRM and cloud platform', true),
('Zoho', 'zoho', 'zoho.com', 'Business software suite', true),
('Freshworks', 'freshworks', 'freshworks.com', 'Customer engagement suite', true),
('Zendesk', 'zendesk', 'zendesk.com', 'Customer service platform', true),
('Intercom', 'intercom', 'intercom.com', 'Customer messaging platform', true),
('Drift', 'drift', 'drift.com', 'Conversational marketing', true),
('Qualified', 'qualified', 'qualified.com', 'Pipeline generation platform', true),
('Gong', 'gong', 'gong.io', 'Revenue intelligence platform', true),
('Chorus.ai', 'chorus-ai', 'chorus.ai', 'Conversation intelligence', true),
('Clari', 'clari', 'clari.com', 'Revenue platform', true),
('Outreach', 'outreach', 'outreach.io', 'Sales engagement platform', true),
('Salesloft', 'salesloft', 'salesloft.com', 'Sales engagement platform', true),
('Apollo', 'apollo', 'apollo.io', 'Sales intelligence platform', true),
('ZoomInfo', 'zoominfo', 'zoominfo.com', 'B2B data platform', true),
('Clearbit', 'clearbit', 'clearbit.com', 'Marketing intelligence', true),
('6sense', '6sense', '6sense.com', 'ABM platform', true),
('Demandbase', 'demandbase', 'demandbase.com', 'Account-based marketing', true),
('Terminus', 'terminus', 'terminus.com', 'ABM platform', true),

-- Developer Tools & Infrastructure
('Vercel', 'vercel', 'vercel.com', 'Frontend cloud platform', true),
('Netlify', 'netlify', 'netlify.com', 'Web development platform', true),
('Railway', 'railway', 'railway.app', 'Infrastructure platform', true),
('Render', 'render', 'render.com', 'Cloud application platform', true),
('Fly.io', 'fly-io', 'fly.io', 'Application hosting platform', true),
('DigitalOcean', 'digitalocean', 'digitalocean.com', 'Cloud infrastructure', true),
('Linode', 'linode', 'linode.com', 'Cloud computing', true),
('Vultr', 'vultr', 'vultr.com', 'Cloud computing', true),
('Hetzner', 'hetzner', 'hetzner.com', 'Web hosting and cloud', true),
('Heroku', 'heroku', 'heroku.com', 'Cloud platform', true),
('Supabase', 'supabase', 'supabase.com', 'Open-source Firebase alternative', true),
('Firebase', 'firebase', 'firebase.google.com', 'App development platform', true),
('MongoDB', 'mongodb', 'mongodb.com', 'Document database', true),
('Redis', 'redis', 'redis.com', 'In-memory database', true),
('Upstash', 'upstash', 'upstash.com', 'Serverless data platform', true),
('PlanetScale', 'planetscale', 'planetscale.com', 'MySQL-compatible database', true),
('CockroachDB', 'cockroachdb', 'cockroachlabs.com', 'Distributed SQL database', true),
('Neon', 'neon', 'neon.tech', 'Serverless Postgres', true),
('Prisma', 'prisma', 'prisma.io', 'Database toolkit', true),
('Hasura', 'hasura', 'hasura.io', 'GraphQL engine', true),
('Apollo GraphQL', 'apollo-graphql', 'apollographql.com', 'GraphQL platform', true),
('Postman', 'postman', 'postman.com', 'API platform', true),
('Insomnia', 'insomnia', 'insomnia.rest', 'API design platform', true),
('Kong', 'kong', 'konghq.com', 'API gateway', true),
('Apigee', 'apigee', 'apigee.com', 'API management', true),
('Twilio', 'twilio', 'twilio.com', 'Communication APIs', true),
('SendGrid', 'sendgrid', 'sendgrid.com', 'Email API', true),
('Mailgun', 'mailgun', 'mailgun.com', 'Email API', true),
('Sendbird', 'sendbird', 'sendbird.com', 'Chat and messaging API', true),
('Stream', 'stream', 'getstream.io', 'Chat and activity feeds', true),
('Pusher', 'pusher', 'pusher.com', 'Realtime infrastructure', true),
('Ably', 'ably', 'ably.com', 'Realtime messaging', true),
('Auth0', 'auth0-identity', 'auth0.com', 'Identity platform', true),
('Clerk', 'clerk', 'clerk.com', 'Authentication for developers', true),
('WorkOS', 'workos', 'workos.com', 'Enterprise-ready APIs', true),
('Stytch', 'stytch', 'stytch.com', 'User authentication', true),
('FusionAuth', 'fusionauth', 'fusionauth.io', 'Authentication platform', true),
('Frontegg', 'frontegg', 'frontegg.com', 'User management platform', true),

-- E-commerce & Payments
('Shopify', 'shopify', 'shopify.com', 'E-commerce platform', true),
('BigCommerce', 'bigcommerce', 'bigcommerce.com', 'E-commerce platform', true),
('WooCommerce', 'woocommerce', 'woocommerce.com', 'WordPress e-commerce', true),
('Magento', 'magento', 'magento.com', 'E-commerce platform', true),
('Swell', 'swell', 'swell.is', 'Headless e-commerce', true),
('Medusa', 'medusa', 'medusajs.com', 'Open-source e-commerce', true),
('Commercetools', 'commercetools', 'commercetools.com', 'Headless commerce', true),
('Fabric', 'fabric', 'fabric.inc', 'Commerce platform', true),
('Bold Commerce', 'bold-commerce', 'boldcommerce.com', 'Checkout platform', true),
('Recharge', 'recharge', 'rechargepayments.com', 'Subscription management', true),
('Chargebee', 'chargebee', 'chargebee.com', 'Subscription billing', true),
('Recurly', 'recurly', 'recurly.com', 'Subscription management', true),
('Paddle', 'paddle', 'paddle.com', 'Payment infrastructure', true),
('FastSpring', 'fastspring', 'fastspring.com', 'E-commerce payments', true),
('Checkout.com', 'checkout-com', 'checkout.com', 'Payment processing', true),
('Adyen', 'adyen-payments', 'adyen.com', 'Payments platform', true),
('Mollie', 'mollie', 'mollie.com', 'Payment service provider', true),
('GoCardless', 'gocardless', 'gocardless.com', 'Direct debit payments', true),
('Modern Treasury', 'modern-treasury', 'moderntreasury.com', 'Payment operations', true),
('Treasury Prime', 'treasury-prime', 'treasuryprime.com', 'Banking-as-a-service', true),
('Unit', 'unit', 'unit.co', 'Embedded banking', true),
('Bond', 'bond', 'bond.tech', 'Enterprise card issuing', true),
('Marqeta', 'marqeta', 'marqeta.com', 'Card issuing platform', true),
('Lithic', 'lithic', 'lithic.com', 'Card issuing API', true),

-- Marketing Tech
('Klaviyo', 'klaviyo', 'klaviyo.com', 'Marketing automation', true),
('Mailchimp', 'mailchimp', 'mailchimp.com', 'Email marketing', true),
('ActiveCampaign', 'activecampaign', 'activecampaign.com', 'Marketing automation', true),
('Brevo', 'brevo', 'brevo.com', 'CRM and marketing', true),
('Customer.io', 'customer-io', 'customer.io', 'Marketing automation', true),
('Iterable', 'iterable', 'iterable.com', 'Cross-channel marketing', true),
('Braze', 'braze', 'braze.com', 'Customer engagement', true),
('OneSignal', 'onesignal', 'onesignal.com', 'Push notifications', true),
('Leanplum', 'leanplum', 'leanplum.com', 'Mobile marketing', true),
('CleverTap', 'clevertap', 'clevertap.com', 'Customer engagement', true),
('MoEngage', 'moengage', 'moengage.com', 'Customer engagement', true),
('WebEngage', 'webengage', 'webengage.com', 'Marketing automation', true),
('Insider', 'insider', 'useinsider.com', 'Growth management', true),
('Optimizely', 'optimizely', 'optimizely.com', 'Experimentation platform', true),
('VWO', 'vwo', 'vwo.com', 'A/B testing platform', true),
('AB Tasty', 'abtasty', 'abtasty.com', 'Experimentation platform', true),
('Statsig', 'statsig', 'statsig.com', 'Feature management', true),
('Eppo', 'eppo', 'geteppo.com', 'Experimentation platform', true),
('GrowthBook', 'growthbook', 'growthbook.io', 'Open-source A/B testing', true),

-- FinTech & Banking
('Robinhood', 'robinhood', 'robinhood.com', 'Investment platform', true),
('Coinbase', 'coinbase', 'coinbase.com', 'Cryptocurrency exchange', true),
('Kraken', 'kraken', 'kraken.com', 'Crypto exchange', true),
('Gemini', 'gemini', 'gemini.com', 'Crypto exchange', true),
('FTX', 'ftx', 'ftx.com', 'Crypto exchange', true),
('Binance', 'binance', 'binance.com', 'Crypto exchange', true),
('Circle', 'circle', 'circle.com', 'Digital finance', true),
('Fireblocks', 'fireblocks', 'fireblocks.com', 'Digital asset custody', true),
('Anchorage', 'anchorage', 'anchorage.com', 'Digital asset platform', true),
('BitGo', 'bitgo', 'bitgo.com', 'Digital asset security', true),
('Chainalysis', 'chainalysis', 'chainalysis.com', 'Blockchain analytics', true),
('Elliptic', 'elliptic', 'elliptic.co', 'Blockchain analytics', true),
('TRM Labs', 'trm-labs', 'trmlabs.com', 'Blockchain intelligence', true),
('Sardine', 'sardine', 'sardine.ai', 'Fraud prevention', true),
('Sift', 'sift', 'sift.com', 'Digital trust and safety', true),
('Forter', 'forter', 'forter.com', 'Fraud prevention', true),
('Riskified', 'riskified', 'riskified.com', 'E-commerce fraud', true),
('Signifyd', 'signifyd', 'signifyd.com', 'Commerce protection', true),
('Onfido', 'onfido', 'onfido.com', 'Identity verification', true),
('IDnow', 'idnow', 'idnow.io', 'Identity verification', true),
('Sumsub', 'sumsub', 'sumsub.com', 'User verification', true),
('Trulioo', 'trulioo', 'trulioo.com', 'Identity verification', true),
('Revolut', 'revolut', 'revolut.com', 'Digital banking', true),
('Wise', 'wise', 'wise.com', 'International money transfer', true),
('Remitly', 'remitly', 'remitly.com', 'Digital remittances', true),
('Nium', 'nium', 'nium.com', 'Global payments', true),
('Rapyd', 'rapyd', 'rapyd.net', 'Fintech-as-a-service', true),
('Payoneer', 'payoneer', 'payoneer.com', 'Payment platform', true),
('Bill.com', 'bill-com', 'bill.com', 'Business payments', true),
('Tipalti', 'tipalti', 'tipalti.com', 'Payables automation', true),
('Stampli', 'stampli', 'stampli.com', 'AP automation', true),
('Airwallex', 'airwallex', 'airwallex.com', 'Business accounts', true),

-- Productivity & Collaboration
('Notion', 'notion-app', 'notion.so', 'Connected workspace', true),
('Coda', 'coda', 'coda.io', 'All-in-one doc', true),
('Roam Research', 'roam', 'roamresearch.com', 'Note-taking tool', true),
('Obsidian', 'obsidian', 'obsidian.md', 'Knowledge base', true),
('Logseq', 'logseq', 'logseq.com', 'Knowledge management', true),
('Craft', 'craft', 'craft.do', 'Document editor', true),
('Mem', 'mem', 'mem.ai', 'AI-powered workspace', true),
('Capacities', 'capacities', 'capacities.io', 'Object-based note-taking', true),
('Tana', 'tana', 'tana.inc', 'Supertool for knowledge work', true),
('Supernotes', 'supernotes', 'supernotes.app', 'Collaborative notes', true),
('Scrintal', 'scrintal', 'scrintal.com', 'Visual note-taking', true),
('Milanote', 'milanote', 'milanote.com', 'Organize creative projects', true),
('Whimsical', 'whimsical', 'whimsical.com', 'Visual workspace', true),
('Excalidraw', 'excalidraw', 'excalidraw.com', 'Virtual whiteboard', true),
('FigJam', 'figjam', 'figma.com/figjam', 'Whiteboard tool', true),
('Lucidchart', 'lucidchart', 'lucidchart.com', 'Diagramming application', true),
('Draw.io', 'drawio', 'diagrams.net', 'Diagramming tool', true),
('Lark', 'lark', 'larksuite.com', 'Collaboration suite', true),
('Feishu', 'feishu', 'feishu.cn', 'Collaboration platform', true),
('Zoom', 'zoom', 'zoom.us', 'Video communications', true),
('Google Meet', 'google-meet', 'meet.google.com', 'Video conferencing', true),
('Microsoft Teams', 'microsoft-teams', 'teams.microsoft.com', 'Collaboration platform', true),
('Webex', 'webex', 'webex.com', 'Video conferencing', true),
('Around', 'around', 'around.co', 'Video calls', true),
('Gather', 'gather', 'gather.town', 'Virtual spaces', true),
('Teamflow', 'teamflow', 'teamflowhq.com', 'Virtual office', true),
('SpatialChat', 'spatialchat', 'spatial.chat', 'Video chat platform', true),

-- Cloud & Infrastructure
('AWS', 'aws', 'aws.amazon.com', 'Cloud computing', true),
('Google Cloud', 'google-cloud', 'cloud.google.com', 'Cloud platform', true),
('Microsoft Azure', 'azure', 'azure.microsoft.com', 'Cloud computing', true),
('Oracle Cloud', 'oracle-cloud', 'oracle.com/cloud', 'Cloud infrastructure', true),
('IBM Cloud', 'ibm-cloud', 'ibm.com/cloud', 'Cloud platform', true),
('Alibaba Cloud', 'alibaba-cloud', 'alibabacloud.com', 'Cloud computing', true),
('Tencent Cloud', 'tencent-cloud', 'cloud.tencent.com', 'Cloud services', true),
('OVH', 'ovh', 'ovhcloud.com', 'Cloud provider', true),
('Scaleway', 'scaleway', 'scaleway.com', 'Cloud infrastructure', true),
('Upcloud', 'upcloud', 'upcloud.com', 'Cloud servers', true),

-- Compliance & GRC
('Vanta', 'vanta-compliance', 'vanta.com', 'Automated compliance', true),
('Drata', 'drata-compliance', 'drata.com', 'Compliance automation', true),
('Secureframe', 'secureframe-compliance', 'secureframe.com', 'Compliance platform', true),
('Thoropass', 'thoropass', 'thoropass.com', 'Compliance platform', true),
('Anecdotes', 'anecdotes', 'anecdotes.ai', 'Compliance OS', true),
('Hyperproof', 'hyperproof', 'hyperproof.io', 'Compliance operations', true),
('LogicGate', 'logicgate', 'logicgate.com', 'GRC platform', true),
('StandardFusion', 'standardfusion', 'standardfusion.com', 'GRC software', true),
('Reciprocity', 'reciprocity', 'reciprocity.com', 'GRC platform', true),
('AuditBoard', 'auditboard', 'auditboard.com', 'Audit management', true),
('Resolver', 'resolver', 'resolver.com', 'Risk management', true),
('ServiceNow GRC', 'servicenow-grc', 'servicenow.com', 'GRC platform', true),
('MetricStream', 'metricstream', 'metricstream.com', 'GRC software', true),
('Archer', 'archer', 'archerirm.com', 'Risk management', true),
('ProcessUnity', 'processunity', 'processunity.com', 'Third-party risk', true),
('Prevalent', 'prevalent', 'prevalent.net', 'Third-party risk', true),
('SecurityScorecard', 'securityscorecard', 'securityscorecard.com', 'Security ratings', true),
('BitSight', 'bitsight', 'bitsight.com', 'Security ratings', true),
('UpGuard', 'upguard', 'upguard.com', 'Cyber risk', true),
('RiskRecon', 'riskrecon', 'riskrecon.com', 'Third-party risk', true),
('Panorays', 'panorays', 'panorays.com', 'Third-party security', true),
('whistic', 'whistic', 'whistic.com', 'Security profile sharing', true),
('OneTrust', 'onetrust', 'onetrust.com', 'Privacy management', true),
('TrustArc', 'trustarc', 'trustarc.com', 'Privacy compliance', true),
('BigID', 'bigid', 'bigid.com', 'Data privacy', true),
('Securiti', 'securiti', 'securiti.ai', 'Data privacy', true),
('Transcend', 'transcend', 'transcend.io', 'Data privacy', true),
('Osano', 'osano', 'osano.com', 'Data privacy platform', true),

-- HR & People Tech
('Workday', 'workday', 'workday.com', 'Enterprise software', true),
('SAP SuccessFactors', 'successfactors', 'sap.com/successfactors', 'HCM software', true),
('Oracle HCM', 'oracle-hcm', 'oracle.com/hcm', 'Human capital management', true),
('ADP', 'adp', 'adp.com', 'HR and payroll', true),
('Paylocity', 'paylocity', 'paylocity.com', 'HR and payroll', true),
('Paycom', 'paycom', 'paycom.com', 'HR technology', true),
('Ceridian', 'ceridian', 'ceridian.com', 'HCM platform', true),
('UKG', 'ukg', 'ukg.com', 'HR solutions', true),
('BambooHR', 'bamboohr', 'bamboohr.com', 'HR software', true),
('Namely', 'namely', 'namely.com', 'HR platform', true),
('Hibob', 'hibob', 'hibob.com', 'HR platform', true),
('Personio', 'personio', 'personio.com', 'HR software', true),
('CharlieHR', 'charliehr', 'charliehr.com', 'HR software', true),
('Factorial', 'factorial', 'factorialhr.com', 'HR software', true),
('Leapsome', 'leapsome', 'leapsome.com', 'People enablement', true),
('15Five', 'fifteen-five', '15five.com', 'Performance management', true),
('Betterworks', 'betterworks', 'betterworks.com', 'Performance management', true),
('Reflektive', 'reflektive', 'reflektive.com', 'Performance management', true),
('Peakon', 'peakon', 'peakon.com', 'Employee engagement', true),
('Qualtrics', 'qualtrics', 'qualtrics.com', 'Experience management', true),
('SurveyMonkey', 'surveymonkey', 'surveymonkey.com', 'Survey platform', true),
('Typeform', 'typeform-surveys', 'typeform.com', 'Forms and surveys', true),
('Tally', 'tally', 'tally.so', 'Form builder', true),
('Jotform', 'jotform', 'jotform.com', 'Form builder', true),

-- Legal Tech
('Ironclad', 'ironclad', 'ironcladapp.com', 'Contract management', true),
('DocuSign', 'docusign', 'docusign.com', 'Digital signatures', true),
('PandaDoc', 'pandadoc', 'pandadoc.com', 'Document automation', true),
('HelloSign', 'hellosign', 'hellosign.com', 'E-signatures', true),
('SignNow', 'signnow', 'signnow.com', 'E-signature solution', true),
('ContractPodAi', 'contractpodai', 'contractpodai.com', 'Contract management', true),
('Agiloft', 'agiloft', 'agiloft.com', 'Contract management', true),
('Juro', 'juro', 'juro.com', 'Contract automation', true),
('Lexion', 'lexion', 'lexion.ai', 'Contract AI', true),
('Kira Systems', 'kira', 'kirasystems.com', 'Contract analysis', true),
('LawGeex', 'lawgeex', 'lawgeex.com', 'AI contract review', true),
('LinkSquares', 'linksquares', 'linksquares.com', 'Contract analytics', true),
('Evisort', 'evisort', 'evisort.com', 'Contract intelligence', true),
('Clio', 'clio', 'clio.com', 'Legal practice management', true),
('MyCase', 'mycase', 'mycase.com', 'Legal software', true),
('PracticePanther', 'practicepanther', 'practicepanther.com', 'Legal software', true),

-- Customer Success & Support
('Gainsight', 'gainsight', 'gainsight.com', 'Customer success', true),
('ChurnZero', 'churnzero', 'churnzero.net', 'Customer success', true),
('Totango', 'totango', 'totango.com', 'Customer success', true),
('Planhat', 'planhat', 'planhat.com', 'Customer platform', true),
('Vitally', 'vitally', 'vitally.io', 'Customer success', true),
('Catalyst', 'catalyst', 'catalyst.io', 'Customer success', true),
('ClientSuccess', 'clientsuccess', 'clientsuccess.com', 'Customer success', true),
('Freshdesk', 'freshdesk', 'freshdesk.com', 'Help desk software', true),
('Help Scout', 'helpscout', 'helpscout.com', 'Customer support', true),
('Front', 'front', 'front.com', 'Customer operations', true),
('Kustomer', 'kustomer', 'kustomer.com', 'CRM platform', true),
('Gladly', 'gladly', 'gladly.com', 'Customer service', true),
('Dixa', 'dixa', 'dixa.com', 'Conversational customer service', true),
('Gorgias', 'gorgias', 'gorgias.com', 'E-commerce helpdesk', true),
('Re:amaze', 'reamaze', 'reamaze.com', 'Customer support', true),
('Crisp', 'crisp', 'crisp.chat', 'Customer messaging', true),
('Tidio', 'tidio', 'tidio.com', 'Customer service platform', true),
('LiveChat', 'livechat', 'livechat.com', 'Customer service', true),
('Olark', 'olark', 'olark.com', 'Live chat', true),
('Tawk.to', 'tawkto', 'tawk.to', 'Live chat', true),

-- More AI & ML Companies
('Runway ML', 'runway-ml', 'runwayml.com', 'AI creative tools', true),
('Midjourney', 'midjourney', 'midjourney.com', 'AI image generation', true),
('Leonardo.AI', 'leonardo-ai', 'leonardo.ai', 'AI image generation', true),
('Ideogram', 'ideogram', 'ideogram.ai', 'AI image generation', true),
('Pika Labs', 'pika', 'pika.art', 'AI video generation', true),
('Synthesia', 'synthesia', 'synthesia.io', 'AI video platform', true),
('HeyGen', 'heygen', 'heygen.com', 'AI video creation', true),
('D-ID', 'd-id', 'd-id.com', 'AI video creation', true),
('ElevenLabs', 'elevenlabs', 'elevenlabs.io', 'AI voice synthesis', true),
('Resemble.AI', 'resemble', 'resemble.ai', 'Voice AI', true),
('PlayHT', 'playht', 'play.ht', 'AI voice generator', true),
('Murf', 'murf', 'murf.ai', 'AI voice generator', true),
('LMNT', 'lmnt', 'lmnt.com', 'AI voice synthesis', true),
('Speechify', 'speechify', 'speechify.com', 'Text to speech', true),
('Otter.ai', 'otter-ai', 'otter.ai', 'AI meeting notes', true),
('Fireflies', 'fireflies', 'fireflies.ai', 'AI meeting assistant', true),
('Grain', 'grain', 'grain.com', 'Meeting intelligence', true),
('Fathom', 'fathom', 'fathom.video', 'AI meeting assistant', true),
('Read.ai', 'read-ai', 'read.ai', 'Meeting intelligence', true),
('Krisp', 'krisp', 'krisp.ai', 'AI noise cancellation', true),
('Descript', 'descript', 'descript.com', 'AI video editing', true),
('Kapwing', 'kapwing', 'kapwing.com', 'Video editing platform', true),
('Lumen5', 'lumen5', 'lumen5.com', 'Video creation', true),
('InVideo', 'invideo', 'invideo.io', 'Video creation', true),
('Pictory', 'pictory', 'pictory.ai', 'AI video creation', true),
('Opus Clip', 'opusclip', 'opus.pro', 'AI video clipping', true),
('Captions', 'captions', 'captions.ai', 'AI video captions', true),
('Wordtune', 'wordtune', 'wordtune.com', 'AI writing assistant', true),
('QuillBot', 'quillbot', 'quillbot.com', 'AI writing tool', true),
('Writesonic', 'writesonic', 'writesonic.com', 'AI writing', true),
('Rytr', 'rytr', 'rytr.me', 'AI writing assistant', true),
('Anyword', 'anyword', 'anyword.com', 'AI copywriting', true),
('Phrasee', 'phrasee', 'phrasee.co', 'AI copywriting', true),
('Peppertype', 'peppertype', 'peppertype.ai', 'AI content', true),
('Sembly', 'sembly', 'sembly.ai', 'AI meeting assistant', true)
ON CONFLICT (slug) DO NOTHING;

-- Update all to ensure they're indexable
UPDATE company_signals SET indexable = true WHERE indexable IS NULL;

-- Confirm final count
SELECT COUNT(*) as total_companies FROM company_signals WHERE indexable = true;
